name: Streamlit App Test # Name of the GitHub Action

on:
  workflow_dispatch: # Manually trigger the workflow
  schedule:
    - cron: "30 21 * * *" # Run the workflow at 2130hrs [UTC] every day
  push:
    branches: [main] # Run when code is pushed to the main branch
  pull_request:
    branches: [main] # Run for pull requests that target the main branch

permissions:
  contents: read # Read the contents of the repository

jobs:
  test: # Name of the job
    runs-on: ubuntu-latest # Operating system for the job
    steps: # Steps to run in the job
      - uses: actions/checkout@v4 # Check out the repository
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12" # Setup Python 3.12
      - uses: streamlit/streamlit-app-action@v0.0.3 # Use the Streamlit App Action
        with:
          app-path: login.py # Path to the Streamlit app
          ### Optional steps to display the test results summary
          pytest-args: -v --junit-xml=test-results.xml # Run pytest with verbose output and save the results in test-results.xml
      - if: always() # Always run the following steps
        uses: pmeier/pytest-results-action@v0.6.0 # Use the pytest-results-action
        with:
          path: test-results.xml # Path to the test results
          summary: true # Display a summary of the test results
          display-options: fEsp # Display the failed, errored, skipped, and passed tests
 